version: '2'
services:
  db:
    image: couchdb:latest    
    ports:
      - "35984:5984"
  web:
    image: node:latest
    volumes:
      - ./functions/core:/usr/sst_functions
      - ./lib:/usr/sst_lib
      - ./params:/usr/sst_params
      - ./test:/usr/src
    environment:
      - SST_FUNCTIONS_HOME=/usr/sst_functions
      - SST_LIB_HOME=/usr/sst_lib
      - SST_PARAMS_HOME=/usr/sst_params
    entrypoint: /usr/src/startup.sh
    ports:
      - "33000:3000"
    depends_on:
      - db